import puppeteer from "puppeteer";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const b=await puppeteer.launch({headless:"new"});
const p=await b.newPage(); await p.setViewport({width:1280,height:800});
let m=0;
await p.setRequestInterception(true);
p.on("request",r=>{if(r.method()==="OPTIONS")return r.respond({status:204,headers:CORS});
 if(r.url().endsWith("/chat")){const s=JSON.parse(r.postData()||"{}");
  return r.respond({status:200,contentType:"application/json",headers:CORS,body:JSON.stringify({reply:"An answer.",thread_id:s.thread_id||`t-${++m}`,sources:[],follow_ups:[]})});}
 if(r.url().endsWith("/api/title"))return r.respond({status:200,contentType:"application/json",headers:CORS,body:JSON.stringify({title:"A title"})});
 if(r.url().includes("/api/games/"))return r.respond({status:404,contentType:"application/json",headers:CORS,body:"{}"});
 r.continue();});
await p.goto("http://localhost:4173/",{waitUntil:"networkidle2"});
await p.type("#aspire-composer","hi"); await p.keyboard.press("Enter");
await new Promise(r=>setTimeout(r,2200));
const v=await p.evaluate(()=>{const t=document.querySelector(".thread");const bar=document.querySelector(".titlebar");
 const mask=getComputedStyle(t).maskImage;
 const barBottom=Math.round(bar.getBoundingClientRect().bottom);
 const stop=/transparent (\d+)px/.exec(mask); const solid=/rgb\(0, 0, 0\) (\d+)px/.exec(mask);
 return {mask:mask.slice(0,90),barBottom,fadeStart:stop?+stop[1]:null,fadeEnd:solid?+solid[1]:null};});
console.log(JSON.stringify(v,null,1));
const visible = v.fadeEnd>v.barBottom;
console.log(visible?`  PASS fade runs ${v.fadeStart}->${v.fadeEnd}px, past the ${v.barBottom}px bar`:"  FAIL fade still occluded");
// reduced motion
const p2=await b.newPage(); await p2.setViewport({width:1280,height:800});
await p2.emulateMediaFeatures([{name:"prefers-reduced-motion",value:"reduce"}]);
await p2.goto("http://localhost:4173/",{waitUntil:"networkidle2"});
await p2.setRequestInterception(true);
p2.on("request",r=>{if(r.method()==="OPTIONS")return r.respond({status:204,headers:CORS});
 if(r.url().endsWith("/chat"))return r.respond({status:200,contentType:"application/json",headers:CORS,body:JSON.stringify({reply:"An answer.",thread_id:"t9",sources:[],follow_ups:[]})});
 if(r.url().endsWith("/api/title"))return r.respond({status:200,contentType:"application/json",headers:CORS,body:JSON.stringify({title:"A title"})});
 if(r.url().includes("/api/games/"))return r.respond({status:404,contentType:"application/json",headers:CORS,body:"{}"});
 r.continue();});
await p2.type("#aspire-composer","hi"); await p2.keyboard.press("Enter");
await new Promise(r=>setTimeout(r,2200));
const rm=await p2.evaluate(()=>getComputedStyle(document.querySelector(".titlebar__text")).animationDuration);
console.log(`  reduced-motion crossfade duration: ${rm}`);
console.log(parseFloat(rm)<=0.01?"  PASS crossfade respects reduced motion":"  FAIL still animating");
await b.close();
