"""Teachable concepts: make the knowledge base something a tutor can teach from

Revision ID: 0016_teachable_concepts
Revises: 0015_staff
Create Date: 2026-08-07

## The problem this table solves

The knowledge base is 706 Q&A rows averaging ~145 characters of answer. That is a
corpus for *answering a question*, and the Q&A agent uses it correctly. It is not
teaching material: a lesson read out of a 145-character row is a definition, and a
definition is not an explanation.

Meanwhile the authored curriculum (`app/curriculum/content/*.yaml`) is real teaching
material and there is one module of it, covering saving. A child asking about
compound interest, inflation, or a scam text message reaches neither -- the KB has
facts about them with no shape to teach, and the curriculum has shape with no lesson
about them.

`concepts` is the join: a teachable unit, synthesised at BUILD time from the KB rows
that support it, carrying its sources so every claim in it can be traced back.

## Why this extends `concepts` rather than creating a second table

`mastery.concept_id` and `lessons.concept_id` are foreign keys onto `concepts.id`.
A parallel `teaching_concepts` table would mean two answers to "what has this child
learned" and two id spaces for spaced repetition to reconcile. There is one concept
space; this migration gives it bodies.

The five existing rows are the curriculum's concepts (`save`, `spend`, `goal`, ...).
They keep their ids -- renumbering them would orphan live mastery rows -- and gain
`slug = id`. Concepts the seeder synthesises get `CON-####` ids. Both kinds are
teachable once they have bodies; the difference is only who authored them.

`module_id` becomes nullable for the same reason: a synthesised concept about
inflation belongs to no authored module, and requiring one would mean inventing
modules to hold single concepts.

## Bodies are per band, and the bands are this product's five

The brief this was built from names four bands. This product has five
(`app/curriculum/schema.py:BANDS`), and `WORD_CAPS`, `BAND_KINDS` and the vocabulary
ladder are all keyed on the five. A fourth-band schema would need a translation layer
at every read site, so the columns follow the product: `body_5_8`, `body_9_12`,
`body_13_15`, `body_16_18`, `body_adult`.

## `status` gates what runtime may serve

`draft` -> resolvable. `needs_review` -> excluded from resolution, because it either
drew fewer than two supporting rows or failed grounding validation. `approved` ->
signed off by the ASPIRE task force. Runtime reads `status <> 'needs_review'`; the
review queue reads the rest.

## `concept_candidates` is the gap list

A question that resolves to no concept and is answered from raw KB rows enqueues a
row here. It is the authoring backlog, generated by real use rather than guessed at.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0016_teachable_concepts"
down_revision: str | None = "0015_staff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Matches `app/db/models.EMBEDDING_DIMENSIONS`. Imported as a literal rather than
#: from the model, because a migration must describe the schema as it was at the
#: moment it ran -- a later dimension change is a later migration, not a silent
#: reinterpretation of this one.
_EMBEDDING_DIMENSIONS = 3072

_STATUSES = "('draft','needs_review','approved')"


def upgrade() -> None:
    # ── the existing five rows keep their ids and gain a slug ────────────────
    op.add_column("concepts", sa.Column("slug", sa.Text(), nullable=True))
    op.execute("UPDATE concepts SET slug = id WHERE slug IS NULL")
    op.alter_column("concepts", "slug", nullable=False)

    op.add_column(
        "concepts",
        sa.Column("locale", sa.Text(), nullable=False, server_default="en"),
    )
    op.add_column("concepts", sa.Column("title", sa.Text(), nullable=True))
    op.execute("UPDATE concepts SET title = name WHERE title IS NULL")
    op.alter_column("concepts", "title", nullable=False)

    op.add_column(
        "concepts",
        sa.Column(
            "aliases",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    op.add_column(
        "concepts",
        sa.Column("domain", sa.Text(), nullable=False, server_default="saving"),
    )

    # One body per band. All nullable: a concept about a mortgage has no 5-8 body
    # and should not pretend to. `resolve` filters on the body the reader's band
    # would receive, so a null body means "not teachable to this reader" rather
    # than "teachable, badly".
    for column in (
        "body_5_8",
        "body_9_12",
        "body_13_15",
        "body_16_18",
        "body_adult",
    ):
        op.add_column("concepts", sa.Column(column, sa.Text(), nullable=True))

    op.add_column("concepts", sa.Column("local_example", sa.Text(), nullable=True))
    op.add_column(
        "concepts",
        sa.Column(
            "misconceptions",
            sa.dialects.postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "concepts",
        sa.Column(
            "check_bank",
            sa.dialects.postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "concepts",
        sa.Column(
            "numeric_anchors",
            sa.dialects.postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "concepts",
        sa.Column(
            "widget_hints",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    # The rows this concept was built from. NOT NULL with an empty default rather
    # than nullable: a concept with no sources is ungrounded, and the grounding
    # validator needs to be able to say so by reading an empty array rather than
    # by distinguishing null from empty.
    op.add_column(
        "concepts",
        sa.Column(
            "source_kb_ids",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    op.add_column(
        "concepts",
        sa.Column("embedding", Vector(_EMBEDDING_DIMENSIONS), nullable=True),
    )
    op.add_column(
        "concepts",
        sa.Column("status", sa.Text(), nullable=False, server_default="draft"),
    )
    op.add_column(
        "concepts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    # A synthesised concept belongs to no authored module.
    op.alter_column("concepts", "module_id", nullable=True)

    op.create_check_constraint("ck_concepts_status", "concepts", f"status in {_STATUSES}")
    op.create_unique_constraint("uq_concepts_slug_locale", "concepts", ["slug", "locale"])
    op.create_index("ix_concepts_status", "concepts", ["status"])
    op.create_index("ix_concepts_domain", "concepts", ["domain"])

    # NO vector index, deliberately, and the same decision `documents` made in
    # migration 0009 for a different reason.
    #
    # pgvector indexes the `vector` type to 2000 dimensions only, and this column
    # is 3072 (`app/db/models.EMBEDDING_DIMENSIONS`). The supported route is an
    # expression index over `embedding::halfvec(3072)`, which is float16 and
    # perturbs cosine scores in the fourth decimal place.
    #
    # That perturbation is affordable for `documents` and is not affordable here.
    # Resolution thresholds are decision boundaries -- 0.62 resolves, 0.45 falls
    # through to RAG-teach -- and a scoring wobble near one of them changes which
    # lesson a child receives. A sequential scan over a table of a few dozen
    # concepts is well under a millisecond; exactness costs nothing and is worth
    # more than an index that is not needed at this size.
    #
    # Revisit if the table reaches four figures, which would mean the ASPIRE task
    # force authored a great deal.

    # ── the gap list ────────────────────────────────────────────────────────
    op.create_table(
        "concept_candidates",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("utterance", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False, server_default="en"),
        sa.Column("age_band", sa.Text(), nullable=False),
        # What retrieval found, so an author can see whether the KB already
        # supports the concept or whether it is a content gap too.
        sa.Column(
            "kb_ids",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column("best_similarity", sa.Float(), nullable=True),
        # How many times this gap has been hit. The ordering column for the
        # authoring backlog -- one child asking once is noise, forty asking is a
        # missing lesson.
        sa.Column("hits", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("resolved_concept_id", sa.Text(), nullable=True),
        sa.UniqueConstraint("utterance", "locale", name="uq_candidate_utterance"),
    )
    op.create_index("ix_candidates_hits", "concept_candidates", ["hits"])


def downgrade() -> None:
    op.drop_index("ix_candidates_hits", table_name="concept_candidates")
    op.drop_table("concept_candidates")

    op.drop_index("ix_concepts_domain", table_name="concepts")
    op.drop_index("ix_concepts_status", table_name="concepts")
    op.drop_constraint("uq_concepts_slug_locale", "concepts", type_="unique")
    op.drop_constraint("ck_concepts_status", "concepts", type_="check")

    # Back to NOT NULL. Any synthesised concept has no module and would block this,
    # so they are removed first -- they are regenerable from the seeder and the
    # authored five are not.
    op.execute("DELETE FROM concepts WHERE module_id IS NULL")
    op.alter_column("concepts", "module_id", nullable=False)

    for column in (
        "created_at",
        "status",
        "embedding",
        "source_kb_ids",
        "widget_hints",
        "numeric_anchors",
        "check_bank",
        "misconceptions",
        "local_example",
        "body_adult",
        "body_16_18",
        "body_13_15",
        "body_9_12",
        "body_5_8",
        "domain",
        "aliases",
        "title",
        "locale",
        "slug",
    ):
        op.drop_column("concepts", column)
