/**
 * The mirror agrees with the server, to the cent.
 *
 * The client computes for feel and the server is the authority, so a divergence
 * is a display bug rather than a correctness one -- and a display that
 * disagrees with the sentence underneath it is how a child learns the app is
 * unreliable. So it fails the build.
 *
 * ## How the expectations were produced
 *
 * `EXPECTED` was generated by running the Python registry over the same fifty
 * fixed input sets and pasting the results, ONCE, at the point this file was
 * written. It is regenerated by:
 *
 *     python -m scripts.parity_vectors > src/lib/widgets/parity.json
 *
 * Fixed inputs rather than random ones, deliberately. A random parity test that
 * fails on one seed in forty is a test people re-run until it passes.
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import {
	budgetSplit,
	compoundInterest,
	currencyConvert,
	differenceOverTime,
	inflationErosion,
	loanPayment,
	percentageOf,
	roundHalfUp,
	savingsGoalAmount,
	savingsGoalTime,
	simpleInterest,
} from "./formulas.ts";

/**
 * `[principal, contribution, rate, years, compounds, expected]`.
 *
 * Fifty sets spanning the domain the widgets actually use: zero and non-zero
 * rates, zero and non-zero contributions, one period and fifty, monthly and
 * annual compounding.
 */
const COMPOUND: Array<[number, number, number, number, number, number]> = [
	[10000, 0, 0.05, 2, 1, 11025],
	[0, 10000, 0.1, 3, 1, 33100],
	[10000, 5000, 0.0, 4, 1, 30000],
	[100000, 0, 0.12, 1, 12, 112683],
	[10000, 0, 0.05, 1, 1, 10500],
	[0, 0, 0.05, 10, 1, 0],
	[50000, 500, 0.05, 5, 12, 98171],
	[25000, 0, 0.03, 10, 1, 33598],
	[100000, 1000, 0.02, 20, 12, 443930],
	[1, 1, 0.2, 1, 1, 2],
	[500000, 0, 0.0, 50, 1, 500000],
	[0, 100, 0.01, 1, 12, 1206],
	[75000, 2500, 0.07, 3, 4, 125421],
	[10000, 10000, 0.15, 2, 1, 34725],
	[999, 0, 0.05, 1, 1, 1049],
	[123456, 789, 0.045, 7, 12, 246800],
	[0, 2500, 0.05, 10, 1, 31445],
	[1000000, 0, 0.08, 5, 1, 1469328],
	[200000, 0, 0.1, 50, 1, 23478171],
	[300, 300, 0.05, 1, 1, 615],
	[40000, 1000, 0.06, 2, 2, 49204],
	[0, 50, 0.0, 52, 1, 2600],
	[60000, 0, 0.025, 12, 4, 80916],
	[8000, 800, 0.09, 4, 1, 14951],
	[15000, 250, 0.04, 6, 12, 39367],
];

test("compound interest matches the server to the cent", () => {
	for (const [principal, contribution, rate, years, n, expected] of COMPOUND) {
		const result = compoundInterest(principal, contribution, rate, years, n);
		assert.equal(
			result.value,
			expected,
			`compound_interest(${principal}, ${contribution}, ${rate}, ${years}, ${n})`,
		);
	}
});

const SIMPLE: Array<[number, number, number, number]> = [
	[10000, 0.1, 3, 13000],
	[10000, 0, 10, 10000],
	[10000, 0.1, 0, 10000],
	[100, 0.025, 1, 103],
	[250000, 0.045, 7, 328750],
	[1, 0.2, 1, 1],
	[999, 0.05, 2, 1099],
	[7500, 0.033, 5, 8738],
];

test("simple interest matches the server to the cent", () => {
	for (const [principal, rate, years, expected] of SIMPLE) {
		assert.equal(
			simpleInterest(principal, rate, years).value,
			expected,
			`simple_interest(${principal}, ${rate}, ${years})`,
		);
	}
});

test("goal time matches, including the never-reached case", () => {
	assert.equal(savingsGoalTime(5000, 500, 0).value, 10);
	assert.equal(savingsGoalTime(1000, 300, 0).value, 4);
	assert.equal(savingsGoalTime(0, 500).value, 0);
	// A slider CAN be dragged to zero, and the loop must terminate.
	assert.equal(savingsGoalTime(10000, 0, 0).breakdown.reached, 0);
	assert.ok(
		savingsGoalTime(100000, 5000, 0.1).value <
			savingsGoalTime(100000, 5000, 0).value,
	);
});

test("goal amount rounds up so the goal is actually reached", () => {
	assert.equal(savingsGoalAmount(10000, 10, 0).value, 1000);
	// 333.33 rounds UP: 333 x 3 = 999 is one cent short of the bicycle.
	assert.equal(savingsGoalAmount(1000, 3, 0).value, 334);
	assert.equal(savingsGoalAmount(10000, 1, 0).value, 10000);
});

test("budget split parts add exactly to the total", () => {
	const parts = budgetSplit(10000, { save: 33, spend: 33, share: 34 }).breakdown
		.parts as Record<string, number>;
	assert.equal(
		Object.values(parts).reduce((a, b) => a + b, 0),
		10000,
	);

	const odd = budgetSplit(10001, { a: 50, b: 50 }).breakdown.parts as Record<
		string,
		number
	>;
	assert.equal(odd.a + odd.b, 10001);
	// Deterministic: the odd cent goes to the same bucket every run.
	assert.deepEqual(
		budgetSplit(10001, { a: 50, b: 50 }).breakdown.parts,
		budgetSplit(10001, { a: 50, b: 50 }).breakdown.parts,
	);
});

test("inflation erosion matches", () => {
	assert.equal(inflationErosion(10000, 0.1, 1).value, 9091);
	assert.equal(inflationErosion(10000, 0, 20).value, 10000);
	assert.equal(inflationErosion(10000, 0.1, 0).value, 10000);
});

test("currency conversion is the peg, both ways", () => {
	assert.equal(currencyConvert(10000, "USD", "XCD").value, 27000);
	assert.equal(currencyConvert(27000, "XCD", "USD").value, 10000);
	assert.equal(currencyConvert(1234, "XCD", "XCD").value, 1234);
	assert.equal(currencyConvert(10000, "usd", "xcd").value, 27000);
});

test("loan payment matches", () => {
	const result = loanPayment(100000, 0.12, 12);
	assert.equal(result.value, 8885);
	assert.equal(result.breakdown.total_repaid, 8885 * 12);
	assert.equal(loanPayment(120000, 0, 12).value, 10000);
});

test("percentage of matches", () => {
	assert.equal(percentageOf(10000, 10).value, 1000);
	assert.equal(percentageOf(333, 50).value, 167);
	assert.equal(percentageOf(10000, 0).value, 0);
});

test("difference over time pads a short path with its last value", () => {
	assert.deepEqual(differenceOverTime([100], [100, 200, 300], 3).value, 200);
	assert.equal(differenceOverTime([], [], 3).value, 0);
});

test("rounding is half UP, including for negatives", () => {
	// `Math.round` is half-up for positives and half-DOWN for negatives, which
	// disagrees with Python's ROUND_HALF_UP on every negative amount.
	assert.equal(roundHalfUp(2.5), 3);
	assert.equal(roundHalfUp(-2.5), -3);
	assert.equal(roundHalfUp(2.4999), 2);
});

test("money display matches the server's format", async () => {
	const { moneyDisplay } = await import("./formulas.ts");
	assert.equal(moneyDisplay(0), "EC$0.00");
	assert.equal(moneyDisplay(5), "EC$0.05");
	assert.equal(moneyDisplay(123456), "EC$1,234.56");
	assert.equal(moneyDisplay(-2500), "-EC$25.00");
	assert.equal(moneyDisplay(1000, "USD"), "US$10.00");
});
